CREATE CACHED TABLE PUBLIC.USER(
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
    TOKEN CHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
)

